### ISSUE TITLE
ValueChangeModeIT.testValueChangeModesForTextArea is flaky and needs to be improved

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin-text-field-flow#205]
You can find the history of `ValueChangeModeIT.testValueChangeModesForTextArea` [here](https://bender.vaadin.com/project.html?projectId=Flow_ComponentSnapshot&testNameId=6838227743585669210&tab=testDetails). And, here is the stack trace:

```
[testValueChangeModesForTextArea[ANY_Chrome_]] java.lang.AssertionError: The value change event should not be sent until timeout elapsed since last event when using ValueChangeMode.TIMEOUT
at com.vaadin.flow.component.textfield.tests.ValueChangeModeIT.assertMessageNotUpdated(ValueChangeModeIT.java:155)
at com.vaadin.flow.component.textfield.tests.ValueChangeModeIT.testValueChangeTimeout(ValueChangeModeIT.java:139)
at com.vaadin.flow.component.textfield.tests.ValueChangeModeIT.testValueChangeModes(ValueChangeModeIT.java:113)
at com.vaadin.flow.component.textfield.tests.ValueChangeModeIT.testValueChangeModesForTextArea(ValueChangeModeIT.java:60)
```

**Comment by pekam** [comment]
This should be solved by commit https://github.com/vaadin/vaadin-text-field-flow/pull/244/commits/5a678d7765189a2042f2d8c066a1189cc6d38811 in PR #244.
